### ISSUE TITLE
[TODO] The list of modules included by the addition

### ISSUE THREAD

**Issue by denji** [Homebrew/homebrew-nginx#49]
List modules
--
*When you are finished working on one of the queries, add the commit message tag `#49`*
* [x] [nginx-unzip-module](https://github.com/youzee/nginx-unzip-module) module allowing the nginx to use files embedded in a zip file (Thanks @milaney)
* [ ] [nginx-http-rdns](https://github.com/flant/nginx-http-rdns) HTTP rDNS module
* [ ] [ngx_http_remote_passwd](https://github.com/x-way/ngx_http_remote_passwd) Basic Auth password available as variable $remote_passwd
* [ ] [ngx_filestats_module](https://github.com/svagner/ngx_filestats_module) module for get statistics about times recieved static content.
* [ ] [ngx_http_status_code_counter](https://github.com/kennon/ngx_http_status_code_counter) keep a count of sent HTTP status codes
* [ ] [ngxtop](https://github.com/lebinh/ngxtop) Real-time metrics for nginx server
* [ ] [ngx_http_autols_module](https://github.com/DvdKhl/ngx_http_autols_module) Flexible nginx auto index module
* [ ] [nginx-ey-balancer](https://github.com/msva/nginx-ey-balancer) haproxy maxconn
* [ ] [encrypted-session-nginx-module](https://github.com/agentzh/encrypted-session-nginx-module) encrypt and decrypt nginx variable values
* [ ] [ngx-http-gm-module](https://github.com/zhaodj/ngx-http-gm-module) nginx http graphicsmagick module
* [ ] [hexin-nginx-module](https://github.com/yinhongzhan/hexin-nginx-module)
* [ ] [nginx-uuid-filter](https://github.com/eliast/nginx-uuid-filter) module for generating cookies using libuuid and hex format
* [ ] [iconv-nginx-module](https://github.com/calio/iconv-nginx-module) character conversion using libiconv
* [ ] [ngx_http_js_module](https://github.com/kung-fu-tzu/ngx_http_js_module) Embedding SpiderMonkey into nginx
* [ ] [nginx-radius](https://github.com/xenols/nginx-radius) nginx radius module
* [ ] [ngx-ip2location](https://github.com/chaizhenhua/ngx-ip2location) Nginx IP2Location Module
* [ ] [nginx-hmac-secure-link](https://github.com/timo2/nginx-hmac-secure-link) Alternative Nginx secure link module with support for MD5, SHA-1, and SHA-2 hashes
* [ ] [couchbase-nginx-module](https://github.com/couchbaselabs/couchbase-nginx-module) module for nginx webserver to access Couchbase Server
* [ ] [ngx_mod_psgi nginx](https://github.com/yko/ngx_mod_psgi) PSGI module
* [ ] [ngx-shared-env](https://github.com/aschlosberg/ngx-shared-env) module for shared hosting environment
* [ ] [ngx_http_url_hash_module](https://github.com/flygoast/ngx_http_url_hash_module) load balance nginx module based on HTTP 302 redirect.
* [ ] [ngx-session-binding-proxy](https://github.com/wburgers/Session-Binding-Proxy) module capable of binding the application session to the SSL session by encrypting the application cookie with a secret key and the SSL master key
* [ ] [nginx-mod-auth-kerb](https://github.com/fintler/nginx-mod-auth-kerb) module to enable the use of SPNEGO, GSSAPI, and Kerberos for HTTP SSO authentication
* [ ] [spnego-http-auth-nginx-module](https://github.com/stnoonan/spnego-http-auth-nginx-module) SPNEGO HTTP Authentication Module for nginx
* [ ] [ngx_empty_cache](https://github.com/moscar09/ngx_empty_cache) module to quickly clean the cache
* [ ] [ngx_http_auth_crowd_module](https://github.com/kare/ngx_http_auth_crowd_module) Provides Crowd authentication for Nginx
* [ ] [nginx_token](https://github.com/jiaohuage/nginx_token) this util is based on Nginx_upstream_hash module, not like the upstream_hash which can only be used for hash total string passed through http request, it can be used for hash one specially word which included in http request.
* [ ] [nginx-length-hiding-filter-module](https://github.com/nulab/nginx-length-hiding-filter-module) BREACH attack nginx filter module to append random generated string to the end of HTML response
* [ ] [nginx-dlg-auth](https://github.com/algermissen/nginx-dlg-auth) module for delegating authentication and authorization to an HTTP gateway.  combines Hawk and iron to enable authentication and authorization using encapsulated tokens
* [ ] [ngx_dynamic_proxy_pass_module](https://github.com/marsqing/ngx_dynamic_proxy_pass_module) module which supports dynamic proxy_pass
* [ ] [ngx_cache_viewer](https://github.com/agile6v/ngx_cache_viewer) module which adds ability to view cache node info from FastCGI, proxy, SCGI and uWSGI caches.
* [ ] [nginx-watermark](https://github.com/vdvm/nginx-watermark) HttpImageFilterModule with watermark support
* [ ] [ngx_http_captcha](https://github.com/fallgold/ngx_http_captcha) nginx captcha module
* [ ] [nginx-http-spent-filter](https://github.com/duhoobo/nginx-http-spent-filter) module which can keep backends' response time in a specified header
* [ ] [ngx_http_upstream_ketama_chash](https://github.com/flygoast/ngx_http_upstream_ketama_chash) nginx load-balancer module implementing ketama consistent hashing.
* [ ] [nginx-dlna-module](https://github.com/arut/nginx-dlna-module) DLNA (Digital Living Network Alliance) makes it possible to share video and audio from your computer to other media devices like TV.
* [ ] [ngx_socks](https://github.com/yangxin0/ngx_socks) nginx module that can offer sock5 service.
* [ ] [strftime-nginx-module](https://github.com/hltbra/strftime-nginx-module) module to write `strftime` formatted time to a nginx conf variable
* [ ] [ngx_http_internal_redirect](https://github.com/flygoast/ngx_http_internal_redirect) module to make an internal redirect to the uri specified according to the condition specified
* [ ] [yy_sec_waf](https://github.com/hnlq715/yy_sec_waf) web application firewall module for nginx, which is already used in the production environment
* [ ] [ngx_small_light](https://github.com/cubicdaiya/ngx_small_light) Dynamic Image Transformation Module.
* [ ] [ngx_http_types_filter](https://github.com/flygoast/ngx_http_types_filter)  module to change the `Content-Type` output header depending on an extension variable
* [ ] [ngx_http_footer_if_filter](https://github.com/flygoast/ngx_http_footer_if_filter) module to add given content to the end of the response according to the condition specified.
* [ ] [ngx_upstream_jdomain](https://github.com/wdaike/ngx_upstream_jdomain) asynchronous domain name resolve module for nginx upstream
* [ ] [nginx_ocsp_proxy-module](https://github.com/kyprizel/nginx_ocsp_proxy-module) OCSP processing module designed for response caching
* [ ] [eflv-nginx-module](https://github.com/publicwrt/eflv-nginx-module) eflv-nginx-module module provides pseudo-streaming server-side support for Flash Video (FLV) files
* [ ] [bodytime-nginx-module](https://github.com/koordinates/bodytime-nginx-module) module to track the time until the client gets sent the first byte of the response body.
* [ ] [nginx-image-filter-watermark](https://github.com/intaro/nginx-image-filter-watermark) Patched image_filter module for Nginx with watermark ability
* [ ] [ngx_http_auth_filter_module](https://github.com/jfstenuit/ngx_http_auth_filter_module) WWW-Authorize filter module for reverse-proxy of IIS resources
* [ ] [summarizer-nginx-module](https://github.com/reeteshranjan/summarizer-nginx-module) Upstream nginx module to get summaries of documents using the summarizer daemon service
* [ ] [sphinx2-nginx-module](https://github.com/reeteshranjan/sphinx2-nginx-module) Nginx upstream module for Sphinx 2.x
* [ ] [nginx-udplog-module](https://github.com/vkholodkov/nginx-udplog-module)
* [ ] [nginx-http-slice](https://github.com/alibaba/nginx-http-slice) module for serving a file in slices (reverse byte-range)
* [ ] [nginx_requestid](https://github.com/hhru/nginx_requestid) sets a variable request_id module
* [ ] [nginx-backtrace](https://github.com/alibaba/nginx-backtrace) module to dump backtrace when a worker process exits abnormally
* [ ] [ngx_cache_purge](https://github.com/FRiCKLE/ngx_cache_purge) module which adds ability to purge content from FastCGI, proxy, SCGI and uWSGI caches.
* [ ] [ngx_slowfs_cache](https://github.com/FRiCKLE/ngx_slowfs_cache) module which adds ability to cache static files.
* [ ] [ngx_coolkit](https://github.com/FRiCKLE/ngx_coolkit) collection of small and useful nginx add-ons.
* [ ] [ngx_zeromq](https://github.com/FRiCKLE/ngx_zeromq) ZeroMQ transport
* [ ] [ngx_supervisord](https://github.com/FRiCKLE/ngx_supervisord) module providing API to communicate with supervisord and manage (start/stop) backends on-demand.
* [ ] [ngx_postgres](https://github.com/FRiCKLE/ngx_postgres) upstream module that allows nginx to communicate directly with PostgreSQL database.
* [ ] [nginx-fluentd-module](https://github.com/fluent/nginx-fluentd-module) module for Fluentd
* [ ] [nginx-http-user-agent](https://github.com/alibaba/nginx-http-user-agent)
* [ ] [nginx_accept_language_module](https://github.com/giom/nginx_accept_language_module) Parse the Accept-Language header and sets a variable
* [ ] [nginx-http-sysguard](https://github.com/alibaba/nginx-http-sysguard) module to protect servers when system load or memory use goes too high.
* [ ] [nginx-mysql-module](https://github.com/arut/nginx-mysql-module) MySQL support in NGINX
* [ ] [nginx-x-rid-header](https://github.com/newobj/nginx-x-rid-header)
* [ ] [nginx-video-thumbextractor-module](https://github.com/wandenberg/nginx-video-thumbextractor-module) module to extract thumbs from a video file
* [ ] [xss-nginx-module](https://github.com/agentzh/xss-nginx-module) Native support for cross-site scripting (XSS)
* [ ] [rds-json-nginx-module](https://github.com/agentzh/rds-json-nginx-module) output filter that formats Resty DBD Streams generated by `ngx_drizzle` and others to JSON
* [ ] [nginx-statsd](https://github.com/zebrafishlabs/nginx-statsd) odule for sending stats to statsd
* [ ] [nginx-http-concat](https://github.com/alibaba/nginx-http-concat) module for concatenating files in a given context: CSS and JS files usually
* [ ] [nginx-upstream-fair](https://github.com/gnosek/nginx-upstream-fair) fair load balancer module for nginx
* [ ] [drizzle-nginx-module](https://github.com/chaoslawful/drizzle-nginx-module) nginx upstream module that talks to mysql and drizzle by libdrizzle
* [ ] [beanstalklog-module](https://github.com/r4um/nginx-beanstalklog-module) Log all http requests to beanstalkd
* [ ] [nginx-gridfs](https://github.com/mdirolf/nginx-gridfs) module for serving files from MongoDB's GridFS
* [ ] [custom-nginx-session-module](https://code.google.com/p/custom-nginx-session-module/)
* [ ] [nginx-cache-control-module](https://code.google.com/p/nginx-cache-control-module/)
* [ ] [ngxv8](https://code.google.com/p/ngxv8/) Nginx module for V8 JavaScript Engine
* [ ] [ltliu-ngx-http-accounting-module](https://code.google.com/p/ltliu-ngx-http-accounting-module/)
* [ ] [nginx-sflow-module](https://code.google.com/p/nginx-sflow-module/) [sFlow](http://www.sflow.org/) monitoring for nginx
* [ ] [nginx-xtoken-module](https://code.google.com/p/nginx-xtoken-module/) nginx module to limit the number of users browsing your website for a time window
* [ ] [nginx_ajp_module](https://github.com/yaoweibin/nginx_ajp_module) support AJP protocol proxy
* [ ] [nginx-upstream-jvm-route](https://code.google.com/p/nginx-upstream-jvm-route/) session stickiness with the session cookie for Nginx
* [ ] [substitutions4nginx](https://code.google.com/p/substitutions4nginx/) a filter module which can do both regular expression and fixed string substitutions for nginx
* [ ] [naxsi](https://code.google.com/p/naxsi/) Naxsi is an open source, high performance, low rules maintenance, Web Application Firewall module for Nginx
* [ ] [nginx-upstream-carp](https://code.google.com/p/nginx-upstream-carp/) upstream module for CARP protocol
* [ ] [ngx_http_modsecurity](https://github.com/SpiderLabs/ModSecurity/tree/master/nginx)
* [ ] [testcookie-nginx-module](https://github.com/kyprizel/testcookie-nginx-module)
* [ ] [nginx-socketlog-module](http://www.binpress.com/app/nginx-socketlog-module/1030) An nginx module for logging http requests via TCP into syslog servers.
* [ ] [ngx-redislog-module](http://www.binpress.com/app/nginx-redislog-module/998) An nginx module for logging http requests into Redis database.
* [ ] [ngineer](https://github.com/DamonOehlman/ngineer) EXPERIMENTAL: Generate proxy routes for nginx
* [ ] [limit_upload_rate](https://github.com/cfsego/limit_upload_rate/) Limit upload rate for nginx
* [ ] [nginx-upload-module](https://github.com/vkholodkov/nginx-upload-module) Uploads using multipart/form-data encoding for nginx
* [ ] [ngx_http_php_memcache_standard_balancer](https://github.com/replay/ngx_http_php_memcache_standard_balancer) loadbalancer that is compatible to the standard loadbalancer in the php-memcache module
* [ ] [ngx_limit_tcp_module](https://github.com/chenbk85/ngx_limit_tcp_module) module used for limiting accept events and concurrent
* [ ] [ngx_hmux](https://github.com/sogou-op/ngx_hmux) Resin's hmux implementation in nginx
* [ ] [nginx_hmux_module](https://github.com/wangbin579/nginx-hmux-module)
* [ ] [ngxsbs](https://github.com/kevin-a-naude/ngxsbs) NginX Server Block Sanitiser * [ ] ensures that user supplied NginX server config is well behaved in a larger/shared context.
* [ ] [ngx_mruby](https://github.com/matsumoto-r/ngx_mruby)
* [ ] [ngx_http_pinba_module](https://github.com/tony2001/ngx_http_pinba_module) Pinba module for nginx
* [ ] [ngx_aws_auth](https://github.com/anomalizer/ngx_aws_auth) nginx module to proxy to authenticated AWS services
* [ ] [ngx_image_thumb](https://github.com/3078825/ngx_image_thumb) Advanced Nginx Image Module
* [ ] [ngx_http_dyups_module](https://github.com/yzprofile/ngx_http_dyups_module) + merge patch Tengine
* [ ] [ngx_http_qrcode_module](https://github.com/dcshi/ngx_http_qrcode_module) Nginx to generate and serve QR code
* [ ] [ngx-lua-stats](https://github.com/skyeydemon/ngx-lua-stats) stats by ngx-lua
* [ ] [ngx_metrics](https://github.com/zenops/ngx_metrics) collect nginx responde code metrics and more
* [x] [ngx_dosdetector](https://github.com/cubicdaiya/ngx_dosdetector) nginx module for detecting Dos attacks (alternative [anti-ddos](https://github.com/marcqualie/homebrew-nginx/blob/master/anti-ddos-nginx-module.rb))
* [ ] [ngx_req_status](https://github.com/zls0424/ngx_req_status) Request status in Nginx
* [ ] [ngx_http_extauth_download](https://github.com/arthurtumanyan/ngx_http_extauth_download) Secure download module for nginx
* [ ] [ngx_http_q_chash](https://github.com/hyuuhit/ngx_http_q_chash) nginx to use consistent hash for upstream, support args, auto retry
* [ ] [ngx_http_gif_magick](https://github.com/mschenck/ngx_http_gif_magick) nginx http filter module for dynamically resizing gifs with ImageMagick
* [ ] [ngx_secure_token](https://github.com/netdna/ngx_secure_token) Token-based authorization module for Nginx.
* [ ] [ngx_access_token](https://github.com/cubicdaiya/ngx_access_token) implement mod_access_token
* [ ] [ngx_http_response_module](https://github.com/catap/ngx_http_response_module)
* [ ] [ngx-sticky-module](https://code.google.com/p/nginx-sticky-module/) nginx module to add an upstream server persistance using cookies
* [ ] [ngx-http-tokenaccess](https://github.com/xiwan/ngx-http-tokenaccess) nginx module to control static resources's access through valid token
* [ ] [ngx_http_allow_methods_module](https://github.com/pschultz/ngx_http_allow_methods_module) Nginx module for allowing custom HTTP methods
* [ ] [ngx_http_ip_tos_filter_module](https://github.com/catap/ngx_http_ip_tos_filter_module) IP TOS module for nginx, implement smart QoS
and traffic shaping at firewall/router level
* [ ] [nginx_ssl_tack](https://github.com/kyprizel/nginx_ssl_tack) patch enables the NGINX SSL module to respond with a TACK TLS Extension

We need a patch
--
* [ ] [ngx_server_info_module](https://github.com/wujiangthu/ngx_server_info_module)
* [ ] [ngx_http_generate_secure_download_links](https://github.com/replay/ngx_http_generate_secure_download_links)

**Comment by laike9m** [comment]
Do you have plans adding [HttpRedis][http://wiki.nginx.org/HttpRedis]?

**Comment by denji** [comment]
@laike9m [HttpRedis2](http://wiki.nginx.org/HttpRedis2Module) Module already supported, pull request are welcome

**Comment by laike9m** [comment]
HttpRedis2 is different from HttpRedis, in many ways...

**Comment by denji** [comment]
@laike9m Homebrew/homebrew-nginx@c5a854a

**Comment by laike9m** [comment]
Great! But I think it's better to call it httpredis rather than redis.

**Comment by jeffrigby** [comment]
I'm having trouble getting cjson (http://www.kyne.com.au/~mark/software/lua-cjson-manual.html#_make) to work correctly when I build it with luarocks or manually. Can we add an option for this in the install? Or is there another way I should be compiling this outside of homebrew?

I get:
dlopen(/usr/local/lib/lua/5.1/cjson.so, 6): Symbol not found: _luaL_setfuncs

**Comment by jeffrigby** [comment]
I've actually figured out how to install cjson manually if anyone is curious:
Install luajit:
brew install luajit

Download cjson from here: 
http://www.kyne.com.au/%7Emark/software/lua-cjson.php

Open the Makefile and change:
LUA_INCLUDE_DIR =   $(PREFIX)/include/
to
LUA_INCLUDE_DIR =   $(PREFIX)/include/luajit-2.0

Run: make install

You will get some warnings but it seems to work fine for me. I saw these warnings when building against non jit lua as well.

**Comment by Mirocow** [comment]
please add ngx_http_accounting_module
